---
- name: Create and Seed Libraries
  hosts: zoslab
  gather_facts: false

  environment: "{{ environment_vars }}"

  collections:
    - ibm.ibm_zos_core

  vars_files:
    - vars/users.yml
    - vars/datasets.yml

  tasks:
    - name: Create seed libraries
      zos_data_set:
        name: "{{ item.dataset }}"
        state: present
        type: pdse
        record_format: fb
        record_length: 80
        block_size: 3120
        space_primary: 5
        space_secondary: 2
        space_type: trk
      loop: >-
        {{
          seed_libraries
          | selectattr('dataset', 'in', missing_datasets)
          | list
        }}
      loop_control:
        label: "{{ item.dataset }}"
      when: missing_datasets | length > 0

    - name: Find seed files
      ansible.builtin.find:
        paths: "{{ playbook_dir }}/seed_files"
        file_type: file
        hidden: yes
        recurse: yes
      delegate_to: localhost
      register: seed_files

    - name: Copy seed files into datasets
      zos_copy:
        src: "{{ item.path }}"
        dest: "TEAM02.SEED.{{ item.path.split('/')[-2] }}({{ item.path.split('/')[-1].split('.')[0] }})"
        remote_src: false
        replace: true
      loop: "{{ seed_files.files }}"